name: Demo

on:
 workflow_dispatch: 
  inputs:
   Env:
    type: choice
    default: Prod
    options:
       - Prod
       - QA
       - DEPLOY
  
      
 
 

env:
     net_worth: 1000000000000000

jobs:
 job1:
   runs-on: ubuntu-latest
   env:
     net_worth: 1000000000000000
   steps:
      - name: print variable
        env:
          net_worth: 2000000
        run: |
         echo "${{ vars.NAME }}"  >> $GITHUB_STEP_SUMMARY
         echo "${{ secrets.PHNO }}"  >> $GITHUB_STEP_SUMMARY
         echo "$net_worth" >> $GITHUB_STEP_SUMMARY
 job2:
    runs-on: ubuntu-latest
    steps:
      - name: display
        run: |
         echo "${{ vars.NAME }}" net worth is $net_worth  >> $GITHUB_STEP_SUMMARY
         echo "${{ github.event.inputs.Env }}" net worth is $net_worth  >> $GITHUB_STEP_SUMMARY
         echo "${{ github.event_name }}"  >> $GITHUB_STEP_SUMMARY
         echo "${{ github.workflow }}"  >> $GITHUB_STEP_SUMMARY   
         echo "${{ github.triggering_actor }}"  >> $GITHUB_STEP_SUMMARY
         echo "${{ github.repository }}"  >> $GITHUB_STEP_SUMMARY

      - name: checkout
        uses: actions/checkout@v4
        with:
  
          ref: main
          path: projects
          fetch-depth: 0

      - name: show
        run: |
         pwd >> $GITHUB_STEP_SUMMARY
         cd projects
         
         ls -l projects >> $GITHUB_STEP_SUMMARY

    
       
         
         
         
             
     
   
  

  
