name: Demo

on:
 push:
   branches: ['main']
      
 
 

env:
     net_worth: 1000000000000000

jobs:
 job1:
   runs-on: ubuntu-latest
   env:
     net_worth: 1000000000000000
   steps:
      - name: print variable
        env:
          net_worth: 2000000
        run: |
         echo "${{ vars.NAME }}"  >> $GITHUB_STEP_SUMMARY
         echo "${{ secrets.PHNO }}"  >> $GITHUB_STEP_SUMMARY
         echo "$net_worth" >> $GITHUB_STEP_SUMMARY
 job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: display
        run: |
         echo "${{ vars.NAME }}" net worth is $net_worth  >> $GITHUB_STEP_SUMMARY
    
         
         echo "${{ github.event_name }}"  >> $GITHUB_STEP_SUMMARY
         echo "${{ github.workflow }}"  >> $GITHUB_STEP_SUMMARY   
         echo "${{ github.triggering_actor }}"  >> $GITHUB_STEP_SUMMARY
         echo "${{ github.repository }}"  >> $GITHUB_STEP_SUMMARY

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: project
          

     
      - name: Run Build Script
      
        run: |
         cd project
         pwd $GITHUB_STEP_SUMMARY
         ls -la  >> $GITHUB_STEP_SUMMARY
         

    
       
         
         
         
             
     
   
  

  
